In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv(r"C:\Users\Dell\Downloads\bank (1).csv")

In [3]:
dataset.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [4]:
dataset.shape

(11162, 17)

In [5]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["deposit"] = le.fit_transform(dataset["deposit"])

In [7]:
dataset.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome  deposit  
0    5   may      1042         1     -1         0  unknown        1  
1    5   may      1467         1     -1         0  unknown        1  
2    5   may      1389         1     -1         0  unknown        1  
3    5   may       579         1     -1         0  unknown        1  
4    5   may       673         2     -1         0  unknown        1

In [8]:
dataset.month.unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb',
       'mar', 'apr', 'sep'], dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
dataset.loan=le.fit_transform(dataset.loan)
dataset.housing=le.fit_transform(dataset.housing)
dataset.default=le.fit_transform(dataset.default)


In [10]:
dataset.poutcome.unique()

array(['unknown', 'other', 'failure', 'success'], dtype=object)

In [11]:
dataset.head()

age         job  marital  education  default  balance  housing  loan  \
0   59      admin.  married  secondary        0     2343        1     0   
1   56      admin.  married  secondary        0       45        0     0   
2   41  technician  married  secondary        0     1270        1     0   
3   55    services  married  secondary        0     2476        1     0   
4   54      admin.  married   tertiary        0      184        0     0   

   contact  day month  duration  campaign  pdays  previous poutcome  deposit  
0  unknown    5   may      1042         1     -1         0  unknown        1  
1  unknown    5   may      1467         1     -1         0  unknown        1  
2  unknown    5   may      1389         1     -1         0  unknown        1  
3  unknown    5   may       579         1     -1         0  unknown        1  
4  unknown    5   may       673         2     -1         0  unknown        1

In [12]:
x=dataset.iloc[:,0:16].values
y=dataset.iloc[:,16:].values

In [13]:
x.shape

(11162, 16)

In [14]:
x

array([[59, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [41, 'technician', 'married', ..., -1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., -1, 0, 'unknown'],
       [43, 'technician', 'married', ..., 172, 5, 'failure'],
       [34, 'technician', 'married', ..., -1, 0, 'unknown']], dtype=object)

In [15]:
y

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [16]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[1,2,3,8,10,15])],remainder="passthrough") 
x=ct.fit_transform(x)

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10000)

In [18]:
x_train

array([[0.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 30, -1, 0],
       [0.0, 0.0, 0.0, ..., 3, -1, 0],
       ...,
       [0.0, 0.0, 1.0, ..., 4, -1, 0],
       [0.0, 0.0, 0.0, ..., 3, -1, 0],
       [0.0, 1.0, 0.0, ..., 8, -1, 0]], dtype=object)

In [19]:
x_test

array([[0.0, 0.0, 0.0, ..., 5, -1, 0],
       [0.0, 1.0, 0.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, 182, 2],
       ...,
       [0.0, 0.0, 0.0, ..., 2, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 6, -1, 0]], dtype=object)

In [20]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
logreg.fit(x_train,y_train)


C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [21]:
ypred=logreg.predict(x_test)

In [22]:
ypred

array([0, 0, 0, ..., 0, 0, 0])

In [23]:
y_test

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [24]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(ypred,y_test)

In [25]:
accuracy

0.8351992834751455

In [26]:
dataset.head(1)

age     job  marital  education  default  balance  housing  loan  contact  \
0   59  admin.  married  secondary        0     2343        1     0  unknown   

   day month  duration  campaign  pdays  previous poutcome  deposit  
0    5   may      1042         1     -1         0  unknown        1

In [27]:
logreg.predict(ct.transform([[60,"technician","married","primary",0,879645,1,0,"unknown",31,"may",1123,23,0,0,"unknown"]]))

array([1])